### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by jgnieuwhof** [resideo/zeus-api#59]
Gateway & service definitions should not live inside the project's `./src` directory.

Ideally each service and gateway would be its own package. This would achieve a few things:
 - Separates the zeus-api core from the service / gateway definitions
 - Allow each service schema to be published in a separate package for re-distribution
 - Allow each service / gateway to define its own server, optionally serving mock-data

**Comment by tazsingh** [comment]
@jgnieuwhof What's the status on this issue? Its scope seems a bit large. Would it help to separate our your list above into separate issues and track them individually?

**Comment by jgnieuwhof** [comment]
@tazsingh - good call, doing so now

**Comment by jgnieuwhof** [comment]
Closed in favour of: #86 / #87 / #88 / #89.
